In [ ]:
# This Python 3 environment comes with many helpful analytics libraries installed
# It is defined by the kaggle/python Docker image: https://github.com/kaggle/docker-python
# For example, here's several helpful packages to load

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

# Input data files are available in the read-only "../input/" directory
# For example, running this (by clicking run or pressing Shift+Enter) will list all files under the input directory

import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

# You can write up to 20GB to the current directory (/kaggle/working/) that gets preserved as output when you create a version using "Save & Run All" 
# You can also write temporary files to /kaggle/temp/, but they won't be saved outside of the current session

In [5]:
#1. Create a 3x3 NumPy array with random integers between 1 and 100. Then, interchange its rows and columns.

import numpy as np

# Create a 3x3 array with random integers between 1 and 100
original_array = np.random.randint(1, 101, size=(3, 3))

# Interchange rows and columns (transpose the array)
transposed_array = original_array.T

# Print the original and transposed arrays
print("Original Array:")
print(original_array)
print("\nTransposed Array:")
print(transposed_array)


Original Array:
[[69 40 99]
 [46 60 62]
 [26 39 10]]

Transposed Array:
[[69 46 26]
 [40 60 39]
 [99 62 10]]


In [6]:
#2. Generate a 1D NumPy array with 10 elements. Reshape it into a 2x5 array, then into a 5x2 array
import numpy as np

# Generate a 1D NumPy array with 10 elements
original_array = np.arange(10)  # Creates an array with elements [0, 1, 2, ..., 9]

# Reshape it into a 2x5 array
reshaped_2x5 = original_array.reshape(2, 5)

# Reshape it into a 5x2 array
reshaped_5x2 = original_array.reshape(5, 2)

# Print the original and reshaped arrays
print("Original Array:")
print(original_array)
print("\nReshaped to 2x5 Array:")
print(reshaped_2x5)
print("\nReshaped to 5x2 Array:")
print(reshaped_5x2)


Original Array:
[0 1 2 3 4 5 6 7 8 9]

Reshaped to 2x5 Array:
[[0 1 2 3 4]
 [5 6 7 8 9]]

Reshaped to 5x2 Array:
[[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]]


In [7]:
#3. Create a 4x4 NumPy array with random float values. Add a border of zeros around it, resulting in a 6x6 array
import numpy as np

# Create a 4x4 array with random float values
original_array = np.random.rand(4, 4)

# Add a border of zeros around the array
bordered_array = np.pad(original_array, pad_width=1, mode='constant', constant_values=0)

# Print the original and bordered arrays
print("Original 4x4 Array:")
print(original_array)
print("\n6x6 Array with Border of Zeros:")
print(bordered_array)


Original 4x4 Array:
[[0.28735849 0.26844352 0.52838755 0.36570202]
 [0.72559351 0.32141227 0.10039434 0.11983864]
 [0.91023822 0.12398434 0.22688753 0.04214888]
 [0.23863287 0.42559279 0.5841695  0.54341263]]

6x6 Array with Border of Zeros:
[[0.         0.         0.         0.         0.         0.        ]
 [0.         0.28735849 0.26844352 0.52838755 0.36570202 0.        ]
 [0.         0.72559351 0.32141227 0.10039434 0.11983864 0.        ]
 [0.         0.91023822 0.12398434 0.22688753 0.04214888 0.        ]
 [0.         0.23863287 0.42559279 0.5841695  0.54341263 0.        ]
 [0.         0.         0.         0.         0.         0.        ]]


In [8]:
#4. Using NumPy, create an array of integers from 10 to 60 with a step of 5.
import numpy as np

# Create an array of integers from 10 to 60 with a step of 5
array = np.arange(10, 61, 5)

# Print the resulting array
print("Array of integers from 10 to 60 with a step of 5:")
print(array)


Array of integers from 10 to 60 with a step of 5:
[10 15 20 25 30 35 40 45 50 55 60]


In [9]:
#5. Create a NumPy array of strings ['python', 'numpy', 'pandas']. Apply different case transformations (uppercase, lowercase, title case, etc.) to each element.
import numpy as np

# Create a NumPy array of strings
array = np.array(['python', 'numpy', 'pandas'])

# Apply different case transformations
uppercase_array = np.char.upper(array)
lowercase_array = np.char.lower(array)
titlecase_array = np.char.title(array)
capitalize_array = np.char.capitalize(array)

# Print the original and transformed arrays
print("Original Array:")
print(array)
print("\nUppercase:")
print(uppercase_array)
print("\nLowercase:")
print(lowercase_array)
print("\nTitle Case:")
print(titlecase_array)
print("\nCapitalize:")
print(capitalize_array)


Original Array:
['python' 'numpy' 'pandas']

Uppercase:
['PYTHON' 'NUMPY' 'PANDAS']

Lowercase:
['python' 'numpy' 'pandas']

Title Case:
['Python' 'Numpy' 'Pandas']

Capitalize:
['Python' 'Numpy' 'Pandas']


In [10]:
#6. Generate a NumPy array of words. Insert a space between each character of every word in the array.
import numpy as np

# Create a NumPy array of words
words_array = np.array(['hello', 'world', 'numpy', 'python'])

# Insert a space between each character of every word
spaced_array = np.char.join(' ', words_array)

# Print the original and modified arrays
print("Original Array:")
print(words_array)
print("\nArray with Spaces Between Characters:")
print(spaced_array)


Original Array:
['hello' 'world' 'numpy' 'python']

Array with Spaces Between Characters:
['h e l l o' 'w o r l d' 'n u m p y' 'p y t h o n']


In [11]:
#7. Create two 2D NumPy arrays and perform element-wise addition, subtraction, multiplication, and division
import numpy as np

# Create two 2D NumPy arrays
array1 = np.array([[1, 2, 3], [4, 5, 6]])
array2 = np.array([[7, 8, 9], [10, 11, 12]])

# Perform element-wise addition
addition_result = array1 + array2

# Perform element-wise subtraction
subtraction_result = array1 - array2

# Perform element-wise multiplication
multiplication_result = array1 * array2

# Perform element-wise division
division_result = array1 / array2

# Print the results
print("Array 1:")
print(array1)
print("\nArray 2:")
print(array2)
print("\nElement-wise Addition:")
print(addition_result)
print("\nElement-wise Subtraction:")
print(subtraction_result)
print("\nElement-wise Multiplication:")
print(multiplication_result)
print("\nElement-wise Division:")
print(division_result)


Array 1:
[[1 2 3]
 [4 5 6]]

Array 2:
[[ 7  8  9]
 [10 11 12]]

Element-wise Addition:
[[ 8 10 12]
 [14 16 18]]

Element-wise Subtraction:
[[-6 -6 -6]
 [-6 -6 -6]]

Element-wise Multiplication:
[[ 7 16 27]
 [40 55 72]]

Element-wise Division:
[[0.14285714 0.25       0.33333333]
 [0.4        0.45454545 0.5       ]]


In [12]:
#8. Use NumPy to create a 5x5 identity matrix, then extract its diagonal elements.
import numpy as np

# Create a 5x5 identity matrix
identity_matrix = np.eye(5)

# Extract the diagonal elements
diagonal_elements = np.diag(identity_matrix)

# Print the identity matrix and its diagonal elements
print("5x5 Identity Matrix:")
print(identity_matrix)
print("\nDiagonal Elements:")
print(diagonal_elements)


5x5 Identity Matrix:
[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]

Diagonal Elements:
[1. 1. 1. 1. 1.]


In [13]:
#9. Generate a NumPy array of 100 random integers between 0 and 1000. Find and display all prime numbers in this array.
import numpy as np

# Function to check if a number is prime
def is_prime(num):
    if num <= 1:
        return False
    for i in range(2, int(num**0.5) + 1):
        if num % i == 0:
            return False
    return True

# Generate a NumPy array of 100 random integers between 0 and 1000
random_array = np.random.randint(0, 1001, size=100)

# Find all prime numbers in the array
prime_numbers = [num for num in random_array if is_prime(num)]

# Print the random array and the prime numbers
print("Random Array:")
print(random_array)
print("\nPrime Numbers in the Array:")
print(prime_numbers)


Random Array:
[ 122  822  348  616  834   91   47  579  711  617  980  871  975  254
  865  967  270  553  712  145  265  557  460  672  520  988  501  410
  632  621  713  806  885  611  544  200  953  593  413  157  995  480
  797  421  396  837  645  824  959  812  792  393  861  169  134   51
  132  341  470  858  383  958   66  319  273  425  765  517  257  780
  403  116  709  214  664  350  862  492  282  119  917  255  282  242
  808  145 1000  452  197  796  484  894  861   72  116  474   78  150
  776  696]

Prime Numbers in the Array:
[47, 617, 967, 557, 953, 593, 157, 797, 421, 383, 257, 709, 197]


In [15]:
#10. Create a NumPy array representing daily temperatures for a month. Calculate and display the weekly averages.
import numpy as np

# Create a NumPy array representing daily temperatures for a month (30 days)
# For demonstration, we'll use random temperatures between 15 and 35 degrees Celsius
daily_temperatures = np.random.uniform(15, 35, size=30)

# Reshape the array to represent 4 weeks (28 days) + 2 extra days
weekly_temperatures = daily_temperatures.reshape(6, 5)

# Calculate the weekly averages
weekly_averages = np.mean(weekly_temperatures, axis=1)

# Print the daily temperatures and weekly averages
print("Daily Temperatures for the Month:")
print(daily_temperatures)
print("\nWeekly Averages:")
print(weekly_averages)


Daily Temperatures for the Month:
[27.85028267 17.12223079 31.09837789 22.8934788  28.7410734  18.37871817
 17.44411668 15.90466292 22.6985381  18.8001144  25.68920291 33.24948056
 22.59069038 26.95499586 19.52196175 32.91433319 32.25689511 24.07654576
 20.03863693 34.75307014 21.74778218 30.33428969 22.99424145 32.60444761
 34.68561867 16.80994767 32.99408435 27.5268901  19.05179699 27.41347446]

Weekly Averages:
[25.54108871 18.64523005 25.60126629 28.80789623 28.47327592 24.75923871]
